<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="SDEVPCSVU7112" name="com.test.regression.cub.testscripts.SignUp" tests="8" failures="0" timestamp="16 Aug 2016 07:28:42 GMT" time="1967.261" errors="2">
  <testcase name="validSignUp_yesIHaveOne" time="287.217" classname="com.test.regression.cub.testscripts.SignUp"/>
  <testcase name="validSignUp4mSL" time="184.663" classname="com.test.regression.cub.testscripts.SignUp"/>
  <testcase name="userNameNPasswordFieldValidationSignUp" time="126.844" classname="com.test.regression.cub.testscripts.SignUp"/>
  <testcase name="validateSignInLinkInSignUpPopup" time="80.381" classname="com.test.regression.cub.testscripts.SignUp"/>
  <testcase name="signUp_validateContactInfoPopup" time="399.015" classname="com.test.regression.cub.testscripts.SignUp">
    <error type="java.lang.AssertionError" message="The following asserts failed:

 Failed for LastName with Special Characters, 
 Failed for LastName with Numbers, 
 Failed for ZIP with alphabets, 
 Failed for CITY with Special Characters, 
 Failed for  CITY with numbers">
      <![CDATA[java.lang.AssertionError: The following asserts failed:

 Failed for LastName with Special Characters, 
 Failed for LastName with Numbers, 
 Failed for ZIP with alphabets, 
 Failed for CITY with Special Characters, 
 Failed for  CITY with numbers
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:37)
	at com.test.regression.cub.testscripts.SignUp.signUp_validateContactInfoPopup(SignUp.java:683)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:75)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:46)
]]>
    </error>
  </testcase> <!-- signUp_validateContactInfoPopup -->
  <testcase name="validSignUp_noCard" time="279.350" classname="com.test.regression.cub.testscripts.SignUp"/>
  <testcase name="validSignUp_yesIHaveOne_validateRewardsPopup" time="316.379" classname="com.test.regression.cub.testscripts.SignUp">
    <error type="java.lang.AssertionError" message="The following asserts failed:

  Failed: No error displayed when user enters invalid cardless id and valid lastname.., 
  Failed: No error displayed when user enters invalid last name and valid  card number.., 
  Failed: No error displayed when user enters invalid Cardles id and valid  card number.., 
  Failed: No error displayed when user enters valid Cardles id and invalid card number.., 
  Failed: No error displayed when user enters valid cardless id and invalid lastname.., 
  Failed: Continue button is enabled  when user enters alphabets in Cardles id feild while adding existing card.., 
  Failed: Continue button is enabled  when user enters Special Characters in Cardles id feild while adding existing card.., 
  Failed: Continue button is enabled  when user enters Space in Cardles id feild while adding existing card.., 
  Failed: No error displayed when user enters invalid card number and valid lastname..">
      <![CDATA[java.lang.AssertionError: The following asserts failed:

  Failed: No error displayed when user enters invalid cardless id and valid lastname.., 
  Failed: No error displayed when user enters invalid last name and valid  card number.., 
  Failed: No error displayed when user enters invalid Cardles id and valid  card number.., 
  Failed: No error displayed when user enters valid Cardles id and invalid card number.., 
  Failed: No error displayed when user enters valid cardless id and invalid lastname.., 
  Failed: Continue button is enabled  when user enters alphabets in Cardles id feild while adding existing card.., 
  Failed: Continue button is enabled  when user enters Special Characters in Cardles id feild while adding existing card.., 
  Failed: Continue button is enabled  when user enters Space in Cardles id feild while adding existing card.., 
  Failed: No error displayed when user enters invalid card number and valid lastname..
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:37)
	at com.test.regression.cub.testscripts.SignUp.validSignUp_yesIHaveOne_validateRewardsPopup(SignUp.java:829)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:75)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:46)
]]>
    </error>
  </testcase> <!-- validSignUp_yesIHaveOne_validateRewardsPopup -->
  <testcase name="validSignUp_noCardButWantOne" time="293.412" classname="com.test.regression.cub.testscripts.SignUp"/>
</testsuite> <!-- com.test.regression.cub.testscripts.SignUp -->
